### ISSUE TITLE
De-uglifying C3 charts

### ISSUE THREAD

**Issue by nanchenchen** [hds-lab/textvisdrg#114]

**Comment by nanchenchen** [comment]
![image](https://cloud.githubusercontent.com/assets/3320040/6521942/db24323c-c392-11e4-9cb8-9b683cff3fc7.png)

**Comment by nanchenchen** [comment]
![image](https://cloud.githubusercontent.com/assets/3320040/6521946/ee9d2940-c392-11e4-9574-50fe4ea85480.png)

**Comment by nanchenchen** [comment]
![image](https://cloud.githubusercontent.com/assets/3320040/6521955/07843660-c393-11e4-830b-d70f813fe787.png)

**Comment by michaelbrooks** [comment]
Row charts. Brilliant. Looks fantastic!
