### ISSUE TITLE
Reformat source indicating text

### ISSUE THREAD

**Issue by nanchenchen** [hds-lab/textvisdrg#227]
This is the current one:
Current Source: time=2014-04-07T12:00:00Z in Group [victim death]

It is super bad

**Comment by mdrouhard** [comment]
Is this issue only intending to change the formatting for the time dimension?

**Comment by mdrouhard** [comment]
in the convert_request_to_readable_str function in msgvis/static/SparQs/controller.js, do the "min_time" and "min" property values only apply to the time dimension?  If so, we can clean up the fix slightly.  Thanks!

**Comment by nanchenchen** [comment]
min_time is time dimension only, and min is for other quan dimensions. :)

2015-11-04 15:30 GMT-08:00 mdrouhard <notifications@github.com>:

> in the convert_request_to_readable_str function in
> msgvis/static/SparQs/controller.js, do the "min_time" and "min" property
> values only apply to the time dimension? If so, we can clean up the fix
> slightly. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hds-lab/textvisdrg/issues/227#issuecomment-153903861>.
>



-- 
Nan-Chen Chen
nanchen.chen@gmail.com
PhD Student
Department of Human Centered Design & Engineering
University of Washington
Seattle, WA 98195
http://nanchen.csie.org/
