### ISSUE TITLE
Retrieve relevant research questions

### ISSUE THREAD

**Issue by michaelbrooks** [hds-lab/textvisdrg#4]
Add a function somewhere in the Questions app that can produce a list of ranked research Question models given a list of dimensions as a parameter.

It should search the database for Questions that involve those dimensions, and sort them by how many dimensions they have in common with the query.

If you can, create a test in `msgvis/apps/questions/tests.py` that shows your method running on some test data.

**Comment by nanchenchen** [comment]
I am not sure if I understand how to use the "Dimension" object in the questions app model. Ideally there should not be things like this:
```python
 question.dimensions.add(Dimension.objects.get_or_create(key="hashtags")[0])
```

I feel the get_dimension method in Dimension looks like a static method for singleton pattern, but it is a member function that have to be called via instances.

**Comment by nanchenchen** [comment]
Currently if there is nothing match I will just return the first 10 questions. We may need to make random filter or partial matching. Or the best solution is to have a way to sort the questions, rather than just filtering.
