### ISSUE TITLE
Put back example messages

### ISSUE THREAD

**Issue by nanchenchen** [hds-lab/textvisdrg#66]
It is disappeared now:
![image](https://cloud.githubusercontent.com/assets/3320040/6424682/e267c11a-beb7-11e4-82c0-fef576e191de.png)

**Comment by michaelbrooks** [comment]
Example messages only load when a filter is specified, currently. Is that the issue you are seeing?

**Comment by nanchenchen** [comment]
Oh I see. I thought we should have some example tweets from the beginning.
