### ISSUE TITLE
Fix data table self-join bug

### ISSUE THREAD

**Issue by michaelbrooks** [hds-lab/textvisdrg#78]
When you ask for a data table for friends and followers you get `(1066, "Not unique table/alias: 'corpus_person'")` because of some issue with self-joining. I'm not sure why it doesn't happen with other person field self-joins...

**Comment by nanchenchen** [comment]
it is rare but still there...

when both quan dimension require grouping

**Comment by michaelbrooks** [comment]
Fixed in 91a68b9ddd0df2172216cf5887d049c143beaa0c
