### ISSUE TITLE
Calculate filter summaries

### ISSUE THREAD

**Issue by michaelbrooks** [hds-lab/textvisdrg#8]
In the dimensions app, add a method to the Dimension object that takes as input a filter (and a corpus) and produces summary statistics (just the count of messages included is fine) that describe how the filter behaves on the dataset. See the [API documentation](http://textvisdrg.readthedocs.org/en/latest/apps/api.html#msgvis.apps.api.views.FilterSummaryView) for details.

Create a test in `msgvis/apps/dimension/tests.py` that shows this method working on test data.

**Comment by nanchenchen** [comment]
We don't need this for API
