### ISSUE TITLE
Default filter on categorical dimensions

### ISSUE THREAD

**Issue by michaelbrooks** [hds-lab/textvisdrg#90]
When you have selected a large categorical dimension, a default filter should be applied that selects the 5-10 most prominent categories. Then you can adjust this manually.

The categorical filter should also display the list of items *included*, not excluded. The inclusion list is always going to be small, while the exclusion list is usually going to be extremely large.

Dimensions with a paired binary dimension (contains_url) are a special case. We should discuss this further to decide how it should work.

**Comment by nanchenchen** [comment]
Do we want to filter all the categorical dimensions by default?

**Comment by nanchenchen** [comment]
Here is the current problem: The filter to 5 categories will not work until the filter is opened and click updated.
![image](https://cloud.githubusercontent.com/assets/3320040/6436522/f36905c8-c065-11e4-9dd5-26f66743f81c.png)

![image](https://cloud.githubusercontent.com/assets/3320040/6436527/ff903a2e-c065-11e4-80aa-ba2b489f6bc9.png)

**Comment by nanchenchen** [comment]
(There are only four because the No hashtags is not working"

**Comment by michaelbrooks** [comment]
This still needs to be fixed I think.
